name = "BoundaryTypes"
uuid = "87732bf5-8483-415b-8bb0-ce5aec1534ed"
version = "0.1.0"
authors = ["daikichiba9511 <daikichiba.tech.ml@gmail.com>"]

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
JSON3 = "1.14"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
